# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Classes
    url: classes/
    weight: 10
  - name: Articles
    url: article-post/
    weight: 20
    Identifier: "article"
  - name: Photography
    url: photography/
    weight: 30
  - name: Public art
    url: public-art/
    Identifier: "article-1"
    Parent: "article"
  - name: Candid
    url: candid/
    Identifier: "article-2"
    Parent: "article"
  - name: Dramatizing Women
    url: dramatizing-women/
    Identifier: "article-3"
    Parent: "article"
 
